# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20151227_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='', max_length=30, verbose_name='login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=30, verbose_name='password'),
        ),
    ]
