# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20151227_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
