# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=30, verbose_name='login')),
                ('password', models.CharField(default='', max_length=30, verbose_name='password')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
            ],
        ),
    ]
