# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=255, verbose_name='url')),
                ('user', models.ManyToManyField(to='Login.User')),
            ],
        ),
    ]
