# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_id', models.IntegerField(verbose_name='subscribe_id')),
                ('url', models.CharField(default='', max_length=255, verbose_name='url')),
            ],
        ),
    ]
